src/Entity/Equipment.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EquipmentRepository")
 */
class Equipment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ShortName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $LongName;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2)
     */
    private $Weight;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\VehicleEquipment", mappedBy="equipment")
     */
    private $equipmentVehicle;

    public function __construct()
    {
        $this->equipmentVehicle = new ArrayCollection();
    }

    public function __toString(): ?string
    {
        return $this->id . " - " . 
        $this->ShortName . " / " .
        $this->LongName . ' (' .
        $this->Weight . ' Kg)';
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getShortName(): ?string
    {
        return $this->ShortName;
    }

    public function setShortName(string $ShortName): self
    {
        $this->ShortName = $ShortName;

        return $this;
    }

    public function getLongName(): ?string
    {
        return $this->LongName;
    }

    public function setLongName(string $LongName): self
    {
        $this->LongName = $LongName;

        return $this;
    }

    public function getWeight(): ?string
    {
        return $this->Weight;
    }

    public function setWeight(string $Weight): self
    {
        $this->Weight = $Weight;

        return $this;
    }

    /**
     * @return Collection|VehicleEquipment[]
     */
    public function getEquipmentVehicle(): Collection
    {
        return $this->equipmentVehicle;
    }

    public function addEquipmentVehicle(VehicleEquipment $equipmentVehicle): self
    {
        if (!$this->equipmentVehicle->contains($equipmentVehicle)) {
            $this->equipmentVehicle[] = $equipmentVehicle;
            $equipmentVehicle->setEquipment($this);
        }

        return $this;
    }

    public function removeEquipmentVehicle(VehicleEquipment $equipmentVehicle): self
    {
        if ($this->equipmentVehicle->contains($equipmentVehicle)) {
            $this->equipmentVehicle->removeElement($equipmentVehicle);
            // set the owning side to null (unless already changed)
            if ($equipmentVehicle->getEquipment() === $this) {
                $equipmentVehicle->setEquipment(null);
            }
        }

        return $this;
    }
}

src/Entity/Vehicle.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VehicleRepository")
 */
class Vehicle
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Matriculation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Brand;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Model;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Color;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\VehicleEquipment", mappedBy="vehicle")
     */
    private $vehicleEquipments;

    public function __construct()
    {
        $this->vehicleEquipments = new ArrayCollection();
    }

    public function __toString(): ?string
    {
        return $this->id;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatriculation(): ?string
    {
        return $this->Matriculation;
    }

    public function setMatriculation(string $Matriculation): self
    {
        $this->Matriculation = $Matriculation;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->Brand;
    }

    public function setBrand(string $Brand): self
    {
        $this->Brand = $Brand;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->Model;
    }

    public function setModel(string $Model): self
    {
        $this->Model = $Model;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->Color;
    }

    public function setColor(string $Color): self
    {
        $this->Color = $Color;

        return $this;
    }

    /**
     * @return Collection|VehicleEquipment[]
     */
    public function getVehicleEquipments(): Collection
    {
        return $this->vehicleEquipments;
    }

    public function addVehicleEquipment(VehicleEquipment $vehicleEquipment): self
    {
        if (!$this->vehicleEquipments->contains($vehicleEquipment)) {
            $this->vehicleEquipments[] = $vehicleEquipment;
            $vehicleEquipment->setVehicle($this);
        }

        return $this;
    }

    public function removeVehicleEquipment(VehicleEquipment $vehicleEquipment): self
    {
        if ($this->vehicleEquipments->contains($vehicleEquipment)) {
            $this->vehicleEquipments->removeElement($vehicleEquipment);
            // set the owning side to null (unless already changed)
            if ($vehicleEquipment->getVehicle() === $this) {
                $vehicleEquipment->setVehicle(null);
            }
        }

        return $this;
    }
}

src/Form/VehicleType.php
<?php

namespace App\Form;

use App\Entity\Vehicle;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VehicleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Matriculation')
            ->add('Brand')
            ->add('Model')
            ->add('Color')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Vehicle::class,
        ]);
    }
}

src/Controller/VehicleController.php
<?php

namespace App\Controller;

use App\Entity\Vehicle;
use App\Entity\VehicleEquipment;
use App\Form\VehicleType;
use App\Repository\VehicleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class VehicleController extends AbstractController
{
    /**
     * @Route("/", name="vehicle_index", methods={"GET"})
     */
    public function index(VehicleRepository $vehicleRepository): Response
    {
        return $this->render('vehicle/index.html.twig', [
            'vehicles' => $vehicleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="vehicle_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $vehicle = new Vehicle();
        $form = $this->createForm(VehicleType::class, $vehicle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($vehicle);
            $entityManager->flush();

            return $this->redirectToRoute('vehicle_index');
        }

        return $this->render('vehicle/new.html.twig', [
            'vehicle' => $vehicle,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/vehicle/{id}", name="vehicle_show", methods={"GET"})
     */
    public function show(Vehicle $vehicle, $id): Response
    {
        return $this->render('vehicle/show.html.twig', [
            'vehicle' => $vehicle,
            'equipments' => $this->getVehicleEquipments($id),
        ]);
    }

    /**
     * @Route("/vehicle/{id}/edit", name="vehicle_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Vehicle $vehicle, $id): Response
    {

        $form = $this->createForm(VehicleType::class, $vehicle);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('vehicle_index');
        }

        return $this->render('vehicle/edit.html.twig', [
            'vehicle' => $vehicle,
            'equipments' => $this->getVehicleEquipments($id),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/vehicle/{id}/delete", name="vehicle_delete", methods={"POST"})
     */
    public function delete(Vehicle $vehicle): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($vehicle);
        $entityManager->flush();

        return $this->redirectToRoute('vehicle_index');
    }

    public function getVehicleEquipments($id)
    {
        $em = $this->getDoctrine()->getManager();
        $vehicleEquipments =
            $em->getRepository(VehicleEquipment::class)->findBy(['vehicle' => $id]);

        return $vehicleEquipments;
    }
}

templates/vehicle/_form.html.twig
{{ form_start(form) }}
{{ form_label(form.Matriculation, 'Immatriculation') }}
{{ form_widget(form.Matriculation, {'attr': {'class': 'text-center mb-3'}}) }}
{{ form_label(form.Brand, 'Marque') }}
{{ form_widget(form.Brand, {'attr': {'class': 'text-center mb-3'}}) }}
{{ form_label(form.Model, 'Modèle') }}
{{ form_widget(form.Model, {'attr': {'class': 'text-center mb-3'}}) }}
{{ form_label(form.Color, 'Couleur') }}
{{ form_widget(form.Color, {'attr': {'class': 'text-center mb-3'}}) }}
<button class="btn btn-success mx-auto d-flex justify-content-center m-3">Valider</button>
{{ form_end(form) }}

templates/vehicle/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition du véhicule
{% endblock %}

{% block body %}
	<h1 class="alert alert-info text-center">Edition du véhicule</h1>
	<div class="container col-8 text-center">
		{% include "vehicle/_form.html.twig" %}
	</div>
	<h3 class="alert alert-secondary text-center d-flex justify-content-center">Equipements présents</h3>
	<table class="table text-center">
		<thead>
			<tr>
				<th>Id</th>
				<th>Nom Court</th>
				<th>Nom Long</th>
				<th>Poids (Kg)</th>
				<th>
					<form class="text-center" action="{{ path('vehicle_equipment_new', {'vehicleId': vehicle.id}) }}" method="post">
						<button type="submit" class="btn btn-success">
							<i class="fa fa-plus fa-lg"></i>
						</button>
					</form>
				</th>
			</tr>
		</thead>
		<tbody>
			{% for equipment in equipments|sort((a, b) => a.weight <=> b.weight) %}
				<tr>
					<td>{{ equipment.equipment.id }}</td>
					<td>{{ equipment.equipment.shortName }}</td>
					<td>{{ equipment.longName }}</td>
					<td>{{ equipment.weight }}</td>
					<td class="d-flex justify-content-center">
						<a href="{{ path('vehicle_equipment_edit', {'vehicle': vehicle.id, 'equipment': equipment.equipment.id}) }}" class="btn btn-warning mr-2">
							<i class="fa fa-pencil fa-lg" aria-hidden="true"></i>
						</a>
						<form action="{{ path('vehicle_equipment_delete', {'equipment': equipment.equipment.id, 'vehicle': vehicle.id}) }}" method="post">
							<button type="submit" class="btn btn-danger">
								<i class="fa fa-trash"></i>
							</button>
						</form>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="6" class="alert alert-warning">Aucun équipment présent sur ce véhicle !</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/vehicle/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des véhicules
{% endblock %}

{% block body %}
	<h1 class="alert alert-info text-center">Liste des véhicules</h1>
	<table class="table text-center">
		<thead>
			<tr>
				<th>Id</th>
				<th>Immatriculation</th>
				<th>Marque</th>
				<th>Modèle</th>
				<th>Couleur</th>
				<th>
					<form class="text-center" action="{{ path('vehicle_new') }}" method="post">
						<button type="submit" class="btn btn-success">
							<i class="fa fa-plus fa-lg"></i>
						</button>
					</form>
				</th>
			</tr>
		</thead>
		<tbody>
			{% for vehicle in vehicles %}
				<tr>
					<td>{{ vehicle.id }}</td>
					<td>{{ vehicle.matriculation }}</td>
					<td>{{ vehicle.brand }}</td>
					<td>{{ vehicle.model }}</td>
					<td>{{ vehicle.color }}</td>
					<td class="d-flex justify-content-center">
						<a href="{{ path('vehicle_show', {'id': vehicle.id}) }}" class="btn btn-info mr-2">
							<i class="fa fa-eye fa-lg" aria-hidden="true"></i>
						</a>
						<a href="{{ path('vehicle_edit', {'id': vehicle.id}) }}" class="btn btn-warning mr-2">
							<i class="fa fa-pencil fa-lg" aria-hidden="true"></i>
						</a>
						<form action="{{ path('vehicle_delete', {'id': vehicle.id}) }}" method="post">
							<button type="submit" class="btn btn-danger">
								<i class="fa fa-trash fa-lg"></i>
							</button>
						</form>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="6" class="alert alert-danger">Aucun véhicule trouvé !</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/vehicle/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouveau véhicule
{% endblock %}

{% block body %}
	<h1 class="alert alert-info text-center">Ajout d'un véhicule</h1>
	<div class="container col-8 text-center">
		{% include "vehicle/_form.html.twig" %}
	</div>
{% endblock %}

templates/vehicle/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails du véhicule
{% endblock %}

{% block body %}
	<h1 class="alert alert-info text-center">Détails du véhicule</h1>
	<div class="d-flex justify-content-center m-3">
		<a href="{{ path('vehicle_index') }}" class="btn btn-info mr-2">
			<i class="fa fa-arrow-left fa-lg" aria-hidden="true"></i>
		</a>
		<a href="{{ path('vehicle_edit', {'id': vehicle.id}) }}" class="btn btn-warning mr-2">
			<i class="fa fa-pencil fa-lg" aria-hidden="true"></i>
		</a>
		<form action="{{ path('vehicle_delete', {'id': vehicle.id}) }}" method="post">
			<button type="submit" class="btn btn-danger">
				<i class="fa fa-trash fa-lg"></i>
			</button>
		</form>
	</div>
	<table class="table d-flex justify-content-center">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ vehicle.id }}</td>
			</tr>
			<tr>
				<th>immatriculation</th>
				<td>{{ vehicle.matriculation }}</td>
			</tr>
			<tr>
				<th>Marque</th>
				<td>{{ vehicle.brand }}</td>
			</tr>
			<tr>
				<th>Modèle</th>
				<td>{{ vehicle.model }}</td>
			</tr>
			<tr>
				<th>Couleur</th>
				<td>{{ vehicle.color }}</td>
			</tr>
		</tbody>
	</table>
	<h3 class="alert alert-secondary text-center">Equipments présents sur ce véhicule</h3>
	<table class="table text-center">
		<thead>
			<tr>
				<th>Id</th>
				<th>Nom court</th>
				<th>Nom Long</th>
				<th>Poids (Kg)</th>
			</tr>
		</thead>
		<tbody>
			{% for equipment in equipments|sort((a, b) => a.weight <=> b.weight) %}
				<tr>
					<td>{{ equipment.equipment.id }}</td>
					<td>{{ equipment.equipment.shortName }}</td>
					<td>{{ equipment.longName }}</td>
					<td>{{ equipment.weight }}</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="6" class="alert alert-warning">Aucun équipement présent sur ce véhicule !</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}